# Generated by Django 2.1.2 on 2018-12-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('italienisch', models.CharField(max_length=60)),
                ('deutsch', models.CharField(max_length=60)),
                ('unit_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.Unit_name')),
            ],
        ),
    ]
