# Generated by Django 2.1.2 on 2019-01-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_unit_name_unit_words'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello',
        ),
    ]
