# Generated by Django 2.1.2 on 2019-01-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_delete_hello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_words',
            name='deutsch',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unit_words',
            name='italienisch',
            field=models.CharField(max_length=200),
        ),
    ]
