# Generated by Django 2.1.2 on 2019-02-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20190122_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_words',
            name='x_times_falsch',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit_words',
            name='x_times_richtig',
            field=models.IntegerField(default=0),
        ),
    ]
