# Generated by Django 2.1.2 on 2019-02-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_auto_20190202_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_words',
            name='word_bei_preufung_falsch',
            field=models.BooleanField(default=False),
        ),
    ]
