# Generated by Django 2.1.2 on 2019-02-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('units', '0007_remove_unit_words_word_bei_preufung_falsch'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_words',
            name='word_bei_preufung_falsch',
            field=models.BooleanField(default=False),
        ),
    ]
