# Generated by Django 2.1.2 on 2019-02-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_unit_words_word_bei_preufung_falsch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit_words',
            name='word_bei_preufung_falsch',
        ),
        migrations.RemoveField(
            model_name='unit_words',
            name='x_times_falsch',
        ),
        migrations.RemoveField(
            model_name='unit_words',
            name='x_times_richtig',
        ),
    ]
