# Generated by Django 2.1.2 on 2019-03-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_auto_20190211_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit_schule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schule', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_sprache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprache', models.CharField(choices=[('IT', 'Italienisch'), ('EN', 'Englisch'), ('RU', 'Russich')], max_length=2)),
            ],
        ),
    ]
