# Generated by Django 2.1.2 on 2019-03-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_unit_schule_unit_sprache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_schule',
            name='schule',
            field=models.CharField(max_length=50),
        ),
    ]
