# Generated by Django 2.1.2 on 2019-03-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0011_auto_20190321_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_name',
            name='schule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Unit_schule'),
        ),
        migrations.AddField(
            model_name='unit_name',
            name='sprache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Unit_sprache'),
        ),
    ]
