# Generated by Django 2.1.2 on 2019-03-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0014_auto_20190321_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit_schule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schule', models.CharField(max_length=50)),
            ],
        ),
    ]
