# Generated by Django 2.1.2 on 2019-03-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0016_remove_unit_name_sprache'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_name',
            name='schule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Unit_schule'),
        ),
        migrations.AddField(
            model_name='unit_name',
            name='sprache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Unit_sprache'),
        ),
        migrations.AlterField(
            model_name='unit_schule',
            name='schule',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unit_sprache',
            name='sprache',
            field=models.CharField(choices=[('IT', 'Italienisch'), ('EN', 'Englisch'), ('RU', 'Russich')], max_length=2),
        ),
    ]
