# Generated by Django 2.1.2 on 2019-03-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0017_auto_20190321_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_schule',
            name='schule',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unit_sprache',
            name='sprache',
            field=models.CharField(choices=[('IT', 'Italienisch'), ('EN', 'Englisch'), ('RU', 'Russich')], max_length=2),
        ),
    ]
