# Generated by Django 2.1.2 on 2019-03-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0020_auto_20190321_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_name',
            name='u_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
