# Generated by Django 2.1.2 on 2019-03-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0021_auto_20190321_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_name',
            name='u_name',
            field=models.CharField(max_length=20),
        ),
    ]
