# Generated by Django 2.1.2 on 2019-04-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0023_anfrage_schule_anfrage_sprache_anfrage_unit_anfrage_words_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_sprache',
            name='sprache',
            field=models.CharField(max_length=20),
        ),
    ]
