# Generated by Django 2.1.2 on 2019-04-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0024_auto_20190418_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprachen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprache_lang', models.CharField(max_length=20)),
                ('sprache_kurz', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='unit_sprache',
            name='sprache',
            field=models.CharField(choices=[('IT', 'Italienisch'), ('EN', 'Englisch'), ('RU', 'Russich')], max_length=2),
        ),
    ]
