# Generated by Django 2.1.2 on 2019-04-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0025_auto_20190418_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_sprache',
            name='sprache',
            field=models.CharField(max_length=2),
        ),
    ]
