# Generated by Django 2.1.2 on 2019-04-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0026_auto_20190418_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit_sprache',
            name='sprache',
        ),
        migrations.AddField(
            model_name='anfrage_sprache',
            name='sprache_kurz',
            field=models.CharField(default='EN', max_length=3),
        ),
        migrations.AddField(
            model_name='unit_sprache',
            name='sprache_kurz',
            field=models.CharField(default='EN', max_length=3),
        ),
        migrations.AddField(
            model_name='unit_sprache',
            name='sprache_lang',
            field=models.CharField(default='Englisch', max_length=20),
        ),
        migrations.AlterField(
            model_name='anfrage_sprache',
            name='sprache',
            field=models.CharField(max_length=20),
        ),
    ]
