# Generated by Django 2.1.2 on 2019-04-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0027_auto_20190418_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anfrage_sprache',
            name='sprache_kurz',
        ),
        migrations.RemoveField(
            model_name='unit_sprache',
            name='sprache_kurz',
        ),
        migrations.RemoveField(
            model_name='unit_sprache',
            name='sprache_lang',
        ),
        migrations.AddField(
            model_name='unit_sprache',
            name='sprache',
            field=models.CharField(choices=[('IT', 'Italienisch'), ('EN', 'Englisch'), ('RU', 'Russich')], default='EN', max_length=2),
        ),
        migrations.AlterField(
            model_name='anfrage_sprache',
            name='sprache',
            field=models.CharField(max_length=100),
        ),
    ]
