# Generated by Django 2.1.2 on 2019-04-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0028_auto_20190418_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anfrage_words_user',
            old_name='words',
            new_name='word_fremdsprache',
        ),
    ]
