# Generated by Django 2.1.2 on 2019-04-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0029_auto_20190418_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='anfrage_words_user',
            name='word_deutsch',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
