# Generated by Django 2.1.2 on 2019-04-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0030_anfrage_words_user_word_deutsch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sprachen',
        ),
        migrations.RemoveField(
            model_name='unit_sprache',
            name='sprache',
        ),
        migrations.AddField(
            model_name='unit_sprache',
            name='sprache_kurz',
            field=models.CharField(default='EN', max_length=3),
        ),
        migrations.AddField(
            model_name='unit_sprache',
            name='sprache_lang',
            field=models.CharField(default='Englisch', max_length=20),
        ),
    ]
