# Generated by Django 2.1.2 on 2019-04-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0031_auto_20190419_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anfrage_sprache',
            name='sprache',
        ),
        migrations.AddField(
            model_name='anfrage_sprache',
            name='sprache_kurz',
            field=models.CharField(default='EN', max_length=3),
        ),
        migrations.AddField(
            model_name='anfrage_sprache',
            name='sprache_lang',
            field=models.CharField(default='Englisch', max_length=20),
        ),
    ]
