# Generated by Django 2.1.2 on 2019-06-03 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0033_auto_20190428_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_words',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
