# Generated by Django 2.1.2 on 2019-07-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0034_unit_words_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_words',
            name='sidenote',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
