# Generated by Django 2.1.2 on 2019-07-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0035_unit_words_sidenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='anfrage_words_user',
            name='sidenote',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
