# Generated by Django 2.1.2 on 2019-07-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0036_anfrage_words_user_sidenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_name',
            name='u_name',
            field=models.CharField(max_length=100),
        ),
    ]
