# Generated by Django 2.1.2 on 2019-07-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0037_auto_20190707_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit_words',
            name='deutsch',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='unit_words',
            name='italienisch',
            field=models.CharField(max_length=500),
        ),
    ]
