# Generated by Django 2.1.2 on 2019-07-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0038_auto_20190708_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anfrage_words_user',
            name='word_deutsch',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='anfrage_words_user',
            name='word_fremdsprache',
            field=models.CharField(max_length=500),
        ),
    ]
