# Generated by Django 2.1.2 on 2019-07-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190701_1204'),
        ('units', '0039_auto_20190710_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_name',
            name='artikel',
            field=models.ManyToManyField(blank=True, to='blog.Post'),
        ),
    ]
