# Generated by Django 2.1.2 on 2019-07-22 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0040_unit_name_artikel'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_name',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 22, 16, 44, 296405, tzinfo=utc)),
        ),
    ]
