# Generated by Django 2.1.2 on 2019-01-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190115_1802'),
    ]

    operations = []

