# Generated by Django 2.1.2 on 2019-01-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190115_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='voc_bits',
            field=models.IntegerField(default=10, max_length=12),
        ),
    ]
