# Generated by Django 2.1.2 on 2019-01-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190115_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_unit',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='voc_bits',
            field=models.IntegerField(default=10),
        ),
    ]
