# Generated by Django 2.1.2 on 2019-01-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190119_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_unit',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
