# Generated by Django 2.1.2 on 2019-01-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190119_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_unit',
            field=models.CharField(default='0', max_length=15),
        ),
    ]
