# Generated by Django 2.1.2 on 2019-01-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190119_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_unit',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
