# Generated by Django 2.1.2 on 2019-01-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190119_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_voc_bits',
            field=models.IntegerField(default=0),
        ),
    ]
