# Generated by Django 2.1.2 on 2019-01-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_first_voc_bits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_voc_bits',
            new_name='first_voc',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_voc',
            field=models.IntegerField(default=0),
        ),
    ]
