# Generated by Django 2.1.2 on 2019-01-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190120_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_zurueck',
            field=models.IntegerField(default=1),
        ),
    ]
