# Generated by Django 2.1.2 on 2019-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_reloaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reloaded',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_zurueck',
        ),
        migrations.AddField(
            model_name='profile',
            name='pruefung_voc',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='voc_bits',
            field=models.IntegerField(default=8),
        ),
    ]
