# Generated by Django 2.1.2 on 2019-01-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190122_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pruefung_umgekehrt',
            field=models.BooleanField(default=False),
        ),
    ]
