# Generated by Django 2.1.2 on 2019-02-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190131_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pruefung_voc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voc', models.CharField(max_length=80)),
            ],
        ),
    ]
