# Generated by Django 2.1.2 on 2019-02-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_pruefung_voc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruefung_voc',
            name='voc',
            field=models.IntegerField(),
        ),
    ]
