# Generated by Django 2.1.2 on 2019-02-04 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0008_unit_words_word_bei_preufung_falsch'),
        ('users', '0024_words_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words_user',
            name='user',
        ),
        migrations.AddField(
            model_name='words_user',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='words_user',
            name='word',
        ),
        migrations.AddField(
            model_name='words_user',
            name='word',
            field=models.ManyToManyField(to='units.Unit_words'),
        ),
    ]
