# Generated by Django 2.1.2 on 2019-02-04 21:35

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('users', '0025_auto_20190204_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='words_user',
            name='word',
        ),
        migrations.DeleteModel(
            name='Words_user',
        ),
    ]
