# Generated by Django 2.1.2 on 2019-02-04 22:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0008_unit_words_word_bei_preufung_falsch'),
        ('users', '0028_auto_20190204_2312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Words_user',
        ),
    ]
