# Generated by Django 2.1.2 on 2019-02-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_words_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words_user',
            name='word',
        ),
    ]
