# Generated by Django 2.1.2 on 2019-02-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_remove_words_user_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words_user',
            name='user',
        ),
        migrations.DeleteModel(
            name='Words_user',
        ),
    ]
