# Generated by Django 2.1.2 on 2019-02-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20190209_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='words_user',
            name='fuer_pruefung',
            field=models.BooleanField(default=False),
        ),
    ]
