# Generated by Django 2.1.2 on 2019-02-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_words_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='words_user',
            name='lernweg_voc',
            field=models.BooleanField(default=True),
        ),
    ]
