# Generated by Django 2.1.2 on 2019-02-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_words_user_lernweg_voc'),
    ]

    operations = [
        migrations.AddField(
            model_name='words_user',
            name='pruefung_reihung',
            field=models.IntegerField(default=0),
        ),
    ]
