# Generated by Django 2.1.2 on 2019-02-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_auto_20190211_2023'),
        ('users', '0041_words_user_pruefung_reihung'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='units_gemacht',
            field=models.ManyToManyField(to='units.Unit_name'),
        ),
    ]
