# Generated by Django 2.1.2 on 2019-02-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_profile_units_gemacht'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='units_gemacht',
            field=models.ManyToManyField(null=True, to='units.Unit_name'),
        ),
    ]
