# Generated by Django 2.1.2 on 2019-02-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20190212_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='units_gemacht',
            field=models.ManyToManyField(blank=True, to='units.Unit_name'),
        ),
    ]
