# Generated by Django 2.1.2 on 2019-03-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='words_user',
            name='fehlertest',
            field=models.BooleanField(default=False),
        ),
    ]
