# Generated by Django 2.1.2 on 2019-03-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20190314_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Unit_name'),
        ),
    ]
