# Generated by Django 2.1.2 on 2019-04-01 17:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_auto_20190320_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unittest_karteikarten',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='unittest_schriftlich',
            field=models.IntegerField(default=0),
        ),
    ]
