# Generated by Django 2.1.2 on 2019-04-01 17:52

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20190401_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unittest_karteikarten',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='unittest_schriftlich',
            field=models.IntegerField(default=1),
        ),
    ]
