# Generated by Django 2.1.2 on 2019-04-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0022_auto_20190321_1801'),
        ('users', '0052_auto_20190401_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unittest_karteikarten',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='unittest_schriftlich',
        ),
        migrations.AddField(
            model_name='profile',
            name='unittest',
            field=models.ManyToManyField(to='units.Unit_words'),
        ),
    ]
