# Generated by Django 2.1.2 on 2019-04-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20190401_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unittest',
            field=models.ManyToManyField(blank=True, to='units.Unit_words'),
        ),
    ]
