# Generated by Django 2.1.2 on 2019-04-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20190401_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unittest',
        ),
    ]
