# Generated by Django 2.1.2 on 2019-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0022_auto_20190321_1801'),
        ('users', '0055_remove_profile_unittest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unittest',
            field=models.ManyToManyField(blank=True, to='units.Unit_words'),
        ),
    ]
