# Generated by Django 2.1.2 on 2019-04-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_profile_unittest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unittest',
        ),
        migrations.AddField(
            model_name='profile',
            name='unittest',
            field=models.CharField(blank=True, max_length=10000000000000, null=True),
        ),
    ]
