# Generated by Django 2.1.2 on 2019-04-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20190402_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unittest',
            field=models.CharField(blank=True, max_length=10000000000000),
        ),
    ]
