# Generated by Django 2.1.2 on 2019-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_auto_20190402_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test_karteikarten',
            field=models.CharField(max_length=100000000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='test_schriftlich',
            field=models.CharField(max_length=10000000000, null=True),
        ),
    ]
