# Generated by Django 2.1.2 on 2019-04-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20190403_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='unittest',
            new_name='unittest_karteikarten',
        ),
        migrations.AddField(
            model_name='profile',
            name='unittest_schriftlich',
            field=models.CharField(max_length=10000000000000, null=True),
        ),
    ]
