# Generated by Django 2.1.2 on 2019-04-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_auto_20190405_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='unittest_karteikarten',
            new_name='testfield',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='test_karteikarten',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='test_schriftlich',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='unittest_schriftlich',
        ),
    ]
