# Generated by Django 2.1.2 on 2019-04-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_auto_20190415_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
