# Generated by Django 2.1.2 on 2019-05-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_auto_20190416_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='testfield',
            field=models.TextField(null=True),
        ),
    ]
