# Generated by Django 2.1.2 on 2019-05-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_auto_20190502_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='karteikarten_voc',
            field=models.IntegerField(default=4),
        ),
    ]
