# Generated by Django 2.1.2 on 2019-05-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_profile_karteikarten_voc'),
    ]

    operations = [
        migrations.AddField(
            model_name='words_user',
            name='umgekehrt',
            field=models.BooleanField(default=False),
        ),
    ]
