# Generated by Django 2.1.2 on 2019-05-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_words_user_umgekehrt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words_user',
            name='umgekehrt',
        ),
    ]
