# Generated by Django 2.1.2 on 2019-07-01 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_remove_words_user_umgekehrt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words_user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 10, 25, 23, 39762, tzinfo=utc)),
        ),
    ]
