# Generated by Django 2.1.2 on 2019-07-01 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0070_auto_20190701_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words_user',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
