# Generated by Django 2.1.2 on 2019-07-01 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20190701_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words_user',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
