# Generated by Django 2.1.2 on 2019-07-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_auto_20190701_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='toleranz',
            field=models.IntegerField(default=51),
        ),
    ]
