# Generated by Django 2.1.2 on 2019-07-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_profile_toleranz'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='group_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='words_user',
            name='group',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pruefung_voc',
            field=models.IntegerField(default=4),
        ),
    ]
