# Generated by Django 2.1.2 on 2019-07-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_auto_20190707_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='words_user',
            name='eingabe',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
