# Generated by Django 2.1.2 on 2019-07-08 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0038_auto_20190708_0949'),
        ('users', '0075_words_user_eingabe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_unit2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.Unit_name'),
        ),
    ]
