# Generated by Django 2.1.2 on 2019-07-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_profile_current_unit2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='pruefung_voc',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='voc_bits',
            field=models.IntegerField(default=6),
        ),
    ]
