# Generated by Django 2.1.2 on 2019-07-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_auto_20190722_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='units_gemacht',
        ),
    ]
