# Generated by Django 2.1.2 on 2019-04-30 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linked',
            field=models.ManyToManyField(blank=True, related_name='linked', to=settings.AUTH_USER_MODEL),
        ),
    ]
