# Generated by Django 2.1.2 on 2019-05-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewed',
            field=models.TextField(null=True),
        ),
    ]
